apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
resources:
- openshift-cert-manager-operator-namespace.yaml 
- openshift-cert-manager-operator-operator-group.yaml
- openshift-cert-manager-operator-sub.yaml
